### ISSUE TITLE
Review Fundamentals of Software v1 (Spanish)

### ISSUE THREAD

**Issue by vikilafarga** [setlife-network/tech-education#10]
Text needs to be reviewed for terminology, flow, and grammatical accuracy.

Another aspect to consider is whether we are open to having two versions, Latin American vs. European, e.g. using “_tomar_” vs. “_coger_”, potential differences in terminology, making better use of regionalisms, etc. Might be overkill, but when reading something of this register (informal, contains idioms, language should be engaging and fun), I think that the more you relate to the language, the better it sticks. Maybe something to file under “some day”.

**Comment by otech47** [comment]
# Los fundamentos del software

# Los fundamentos del software

Defiéndete contra un mercado laboral turbulento en esta época de crecimiento exponencial.

## **Introducción**

El objetivo principal de este curso es establecer los conceptos fundamentales de la programación utilizando unos ejemplos prácticos y reconocibles. Muchas personas ven la programación como algo abrumador e incluso amenazante al principio y pueden no tener la confianza para dedicar el tiempo necesario para realizar un curso completo de software.

La verdad es que programar se acerca mucho más a leer y escribir una historia cuando sabes qué cosas buscar. Nuestro objetivo es ayudar a personas con las ganas suficientes a encontrar la confianza antes de que elijan un lenguaje de programación y empiecen a aprender y por tanto el trabajo práctico de escribir programas queda fuera del alcance de este curso. Sin embargo, hay una sección al final con un esquema general para aprender Javascript junto con recursos informativos gratuitos y recomendaciones sobre cursos de pago.

La versión actual de este curso es la 1.0 y un principiante debería poder digerir el material completamente en menos de 30-60 minutos. Hay temas avanzados que se ampliarán en una versión futura, así como enlaces a recursos externos que pueden proporcionar más detalles o claridad.

# Los **fundamentos**

- La secuencia de comandos y la secuencia de eventos
- La declaración de variables
- La lógica del condicional
- La lógica y el algebra booleanos
- Los objetos y los pares de claves y valores
- Las construcciones iterativas

# La secuencia de órdenes y la secuencia de eventos

Una forma de describir un programa podría ser la serie de órdenes generalmente escritos de arriba hacia abajo, con cada orden en una línea nueva, y una vez que el programa haya comenzado, cada línea **se llama** o **se activa** en esta orden secuencial. En este contexto, podemos referirnos a estas líneas de código como una secuencia de *órdenes* o una secuencia de *eventos* donde la diferencia es la perspectiva, relativa al punto de vista.

1. Si te refieres a la secuencia mientras escribes el código, puedes ver a cada línea como una orden que será llamado en algún momento futuro.
2. Si se refiere a la secuencia mientras el programa está en ejecución, puedes ver a cada línea como un evento que está ocurriendo en tiempo real.

Esto crea dos ámbitos contextuales a la hora de pensar en un programa, uno sirve para predecir lo que va a suceder en el futuro y el otro para entender lo que está sucediendo en un momento dado.

Imagínate que te haces un amigo nuevo y le pides su número de teléfono para apuntarlo. Básicamente estás escribiendo una serie de órdenes como referencia para poder llamarlos más tarde. Si te quieres comunicar con tu amigo en ese momento, obviamente solo hace falta hablar porque lo tienes ahí mismo y te podrá oír, pero para comunicarte en el futuro cuando ya no esté, sabes que tendrás que sacar tu teléfono, marcar la serie de números e iniciar una llamada de voz. En cierto modo, estás guardando las instrucciones para más tarde.

Si esto te parece sencillo es porque lo haces automáticamente todos los días sin tener que pensar cómo lo describirías. Conceptualmente, todo lo que vemos sucede en una secuencia continua a medida que sentimos que el tiempo avanza del pasado al futuro. Esto es un proceso natural que los humanos siempre hemos observado, pero ahora somos capaces de replicar este proceso usando computadoras escribiendo y ejecutando estas líneas de código fuente.

No lo pienses demasiado, es tan sencillo como suena. A medida que aprendas más sobre la programación, habrán matices más avanzados que resultarán muy importantes a la hora de averiguar qué se supone que tiene que hacer una secuencia muy larga de órdenes.

## Temas avanzados

El comportamiento de las funciones, la callback y la programación asíncrona

# Declaración de variables

Declarar una variable es simplemente reconocer que se ha hecho una observación. El *nombre* que les des a la variable podría ser `roca` o `árbol`, o `númeroDeÁrboles` para este ejemplo. Todavía no importa el *valor*, sólo hay que declarar que existe. Esto es importante principalmente para poder hacer referencia a nuestro `númeroDeÁrboles` más abajo en la secuencia de órdenes para fijarle un *valor* de `4` ó `cinco` ó `1000`. Las variables son mucho más útiles cuando tienen un *valor*. Podemos declarar una variable e inmediatamente darle un valor en la misma línea, o declararla primero, y luego asignarle el valor en una línea diferente que será ejecutada más tarde.

Supongamos que el `numeroDeArboles` en el jardín es `3`. Si en cambio dijeras, por la razón que fuera, que el `numeroDeArboles` es `azul`, tu programa técnicamente lo "permitiría", pero mucho sentido no tendría y por tanto tu programa realmente no le sería muy útil al que quiera entender lo que estás programando. Si quieres que otros programadores lo puedan mejorar, es importante que el lenguaje utilizado en tu programa se lea naturalmente en este sentido. También te sirve para en un futuro poder recordar por qué escribiste tu programa de una manera y no otra. El dominio de la gramática y vocabulario son imprescindibles a la hora declarar variables con fluidez y con una clara intención de lo que quieres que haga el programa. Tal vez `numeroDeArbolesEnElJardín` o `numeroDeRobles` son descriptores más precisos para sus propósitos.

Otra forma de ver una variable es imaginarse guardando cosas en una caja vacía. Le puedes poner cualquier etiqueta a cualquier caja y meter adentro lo que quieras. Una caja etiquetada como `agua` puede contener un montón de botellas de agua de plástico o tal vez un par de jarrones de agua. Tú decides qué tan precisa debería ser la etiqueta (`jarronesDeAgua`, `botellasDeAgua`, etc.). La etiqueta de la caja es el *nombre* de tu variable y lo que le metas dentro es su *valor*. Puedes cerrar la caja y llevarla a donde quieras a lo largo del programa. Siempre puedes volver a abrirlo, comprobar que todo está como lo dejaste, sacar una jarrón, meter más botellas, etc. Tus cajas de variables permanecen accesibles a tu programa para uso futuro y representan una forma fundamental de "almacenar datos".

Nuevamente no hay que pensar demasiado en lo sencillo que esto se relaciona con lo que tu mente y tus sentidos te describen a lo largo del día:

- El *sol* está **caliente**
- Mis *ojos* están **abiertos**
- Ese *árbol* es **alto**

Declarar una variable es sólo una forma fácil de decir "esto es así", en la que te aseguras de darle a "esto" un nombre que tenga sentido y "así" es un valor que tiene sentido lógico y está relacionado con el nombre que elegiste.

**Temas avanzados**

- Posibles tipos de variables
- Cómo crear y destruir variables y cómo gestionarlas en diferentes ámbitos

# La lógica del condicional

Todo el mundo utiliza la lógica condicional prácticamente todo del día a todas horas, sin siquiera pensar en ello. Solo cuando reflexionas sobre ello podrás abrir la mente a las posibilidades de programación. La idea básica es esta:

- Si se cumple esta condición, entonces haz aquello,
- Si no se cumple esta condición (se cumple cualquier otra), haz lo otro
- Reemplace las palabras en negrita para reflejar la decisión que quieres que se tome.

Por ejemplo, digamos que tienes una vaso de agua en frente y quieres decidir si la quieres levantar con la mano, llevártela a la boca y beber. Una condición que tu cerebro quiere verificar instintivamente es si la taza contiene agua o no. Si `vasoEstáVacío` es `verdadero` entonces sabes que no hace falta ni agarrar el vaso. Si en cambio `vasoEstáVacío` es `falso` entonces ya podríamos verificar otra condición, si la taza está o no al alcance de tus manos. Si `vasoEstáAlAlcance` es `verdadero` pues se cumpla una segunda condición que es necesaria para poder beber. La combinación de varias condiciones tendrá mucho más sentido después de que hablar sobre la lógica y algebra booleanos en la siguiente sección.

# La lógica y el algebra booleanos

Es relativamente fácil entender `verdadadero` y `falso`. O `vasoEstáVacío` es verdadero, o el vaso no está vacío. Ya que no hay más que estas dos opciones, es una simple respuesta de sí o no. En general queremos conseguir reducir las cosas a un sí o no, pero a veces es útil usar ecuaciones matemáticas en combinación con nuestra lógica condicional.

En nuestro ejemplo con el vaso de agua, tenemos una base generalizada para decidir comprobando si `vasoEstáVacío` es verdadero o falso. Podemos matematizar esta idea describiendo una variable llamada `litrosDeAguaEnVaso` y comprobando si el valor de esa variable es `0`. Si hay mas de 0 litros, podemos estar seguros de que hay al menos algo de agua en el vaso y con esa condición lógica, decidimos que vale la pena beber.

Podemos usar el concepto matemático de las desigualdades para decidir si hay suficiente agua en el vaso para beber (por ejemplo, `litrosDeAguaEnVaso > 0`). Aquí hay muchas ideas paralelas a la aritmética básica, pero para simplificar las cosas por ahora, digamos que el álgebra booleana nos permite combinar múltiples condiciones que podemos entender lógicamente usando las siguientes operaciones.

AND Con el operador AND, es necesario que ambas condiciones sean verdaderas

OR Con el operador OR, es necesario que al menos 1 condición sea verdadera

# Los objetos y los pares de claves y valores

El concepto del par clave-valor es parecida a la de una variable y su valor, pero conceptualizado de manera un poco distinta. Sencillamente, tienes un nombre que describe algo, por ejemplo `númeroDeÁrboles` y lo denominas la *clave* que mas tarde te permitirá “acceder” a un *valor* de `4` con el que ha sido *emparejado* previamente. Cuando tienes muchas llaves, es importante saber que todas estén emparejadas con un valor determinado.

Al igual que las variables, los pares clave-valor pueden ser cualquier cosa así que dejaré algunos ejemplos a continuación:

Clave

`colorDelÁrbol`

`alturaDelÁrbolEnMetros`

`númeroDeHojasEnÁrbol`

`anchoDelTroncoEnCentímetros`

`tipoDeÁrbol`

Valor

"marrón"

6

143

100

"roble"

El concepto del *objeto* es particularmente abstracto, pero básicamente nos permite tomar nuestras variables y pares clave-valor y organizarlos para entender lo que nuestro programa está haciendo. ¿Estamos hablando de un solo árbol en el patio de alguien? ¿O un bosque entero de árboles que abarca cientos de hectáreas? Para hacer este salto de comprensión, tendremos que distinguir entre pares clave-valor y variables.

Fijándote en la tabla anterior verás que todas las claves describen cualidades de `árbol`. Tenemos cinco pares clave-valor que actúan como cinco cajas variables que guardan información sobre cinco características diferentes de `árbol`. Podría resultar difícil de manejar el tener que estar pendiente de 5 variables diferentes sueltos por allí a lo largo del código. Definiendo un *objeto*, podemos agruparlos todos juntos en una sola variable llamada `árbol`, o tal vez `Árbol`, para indicar que no es exactamente lo mismo que una variable normal y corriente (no olvides utilizar tus capacidades lingüísticas).

Imagínate un cofre grande con compartimentos internos convenientemente etiquetados, cada uno que contiene 1 de las 5 cajas de variables que anteriormente manejábamos individualmente. Los objetos nos vienen útil para organizar las variables en pares clave-valor y tenerlas todas a mano mientras escribes y trabajas en el programa.

A partir de aquí la analogía visual de las cajas y los cofres pierde algo de utilidad, ya que no hay límite de número de cajas que podemos colocar dentro de los cofres, para luego colocarlas dentro de cofres cada vez más grandes. Podríamos definir otro objeto llamado `Bosque` que contiene 100 `árboles` diferentes, todos con diferentes valores para el `color` o la `alturaEnMetros` o el `númeroDeHojas`. Podríamos continuar así y definir un objeto aún más grande llamado `Norteamérica` que contiene miles de `Bosques` cada uno con sus cientos de `Árboles` etcétera.

Esta idea puede ser abrumadora a escalas mas grandes. Los programas que son capaces de tener claro todos estos objetos dentro de objetos necesitan *construcciones iterativas* robustas para ayudarnos a nosotros entender qué hacer con todos estos `Árboles` y `Bosques` sin comernos el coco llevando el registro de todas las variables. Échale un vistazo a la siguiente sección para más información básica sobre este tema.

# Las construcciones iterativas

Aquí es donde las cosas empiezan a ser mas interesantes. Una iteración es un conjunto de instrucciones que se ejecutan de principio a fin y que luego se pueden repetir. Pongamos que tienes 20 botellas de agua sobre una mesa. Quieres guardarlos todos en la despensa y sólo puedes llevar dos botellas a la vez. Para completar esta tarea, empezando con estar al lado de la mesa, tendrías que hacer lo siguiente:

1. Tomar dos botellas con las manos
2. Caminar a la despensa
3. Identificar un lugar adecuado para las dos botellas
4. Colocar las dos botellas en su lugar
5. Volver a la mesa
6. Tomar otras dos botellas con las manos
7. Regresar a la despensa
8. Identificar un lugar adecuado para las dos otras botellas
9. Colocar éstas dos botellas en su lugar
10. Volver a la mesa

Te habrás dado cuenta de que estoy escribiendo las mismas líneas una y otra vez. Esto es una indicación de que puedes utilizar una construcción iterativa para ahorrar tiempo, en lugar de repetir las mismas líneas de código y mas veces de lo necesario. Podrías simplemente tomar los pasos del 1 al 5 y acordarte de repetir la secuencia diez (10) veces para asegurarte de que las 20 botellas lleguen a la despensa. Mientras puedas ver que `númeroDeBotellasEnMesa` disminuye cada vez que las recoges, o que `númeroDeBotellasEnDespensa` aumenta cada vez que las colocas, sabrás exactamente en qué punto obligarle al programa dejar de repetir los pasos del 1 al 5. Antes de que se active el paso 1, simplemente declararías algunas variables, vigilarías sus valores con un poco de lógica condicional y tu construcción iterativa debería saber exactamente qué hacer para completar la tarea.

Hay unos cuantos tipos de construcciones iterativas diferentes, pero no vamos a entrar en eso todavía. Con que entiendas que tienes la posibilidad de repetir un conjunto de instrucciones hasta que hayas alcanzado una meta determinada, el resto es semántica y usar la sintaxis apropiada.

## Temas avanzados

- Iteraciones infinitas
- Filtrado, mapeo y reducción

# Aprender a escribir programas

Si quieres empezar a aprender a escribir programas y hacer la prueba, aquí tienes un resumen general dirigido al que no ha escrito nunca un programa:

1. Léete el [tutorial de JavaScript de W3Schools (en inglés)](https://www.w3schools.com/js/default.asp) desde el principio. Cuando llegues a lo de JS Bitwise, puedes dejarlo y pasar al número 2, ya que allí es cuando empiezan los temas mas avanzados.
2. Revisa los fundamentos aquí descritos y trata en serio de escribir algunas líneas de código en JavaScript que demuestre cada principio (por ejemplo, `var vasoEstaVacio = true`)
3. Mírate este vídeo con [ejemplos de programación en Java](https://www.youtube.com/watch?v=WPvGqX-TXP0), a velocidad normal. También puedes mirar a ver cómo usar Eclipse y hacer lo que hace él junto con el vídeo. Los principiantes muchas veces cometen el error de preocuparse por escoger un solo idioma y aprenderlo bien, pero no hace falta. Traducir entre Java y Javascript puede ser útil en algunos casos raros, pero una persona verdaderamente alfabetizada en software es capaz de usar estos fundamentos de programación para analizar y entender lo que hace un programa, independientemente de la sintaxis o el lenguaje.
4. Practica con el JavaScript usando el [Console de DevTools de Google](https://developers.google.com/web/tools/chrome-devtools/console/) mientras te leas los primeros dos capítulos de *[You Don't Know Javascript: Up & Going](https://github.com/getify/You-Dont-Know-JS/tree/master/up%20%26%20going)* (en inglés). El capítulo “Strict Mode” es un buen punto de parada.
