### ISSUE TITLE
Translate Fundamentals of Software v1 to Spanish

### ISSUE THREAD

**Issue by otech47** [setlife-network/tech-education#5]
Current progress:
https://www.notion.so/setlife/Spanish-7-8-sections-translated-8ac3644a9c234eb98f2b69524322a343

**Comment by vikilafarga** [comment]
Just one section left before I can hand it off to a reviewer. Have two native-Spanish-speaking programmer friends I can ask.

**Comment by vikilafarga** [comment]
Just finished translating the last section and will add the text file. Next step is to have the text reviewed.
